# Generated by Django 4.2 on 2023-05-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "sname",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("sage", models.IntegerField()),
            ],
        ),
    ]
